"""empty message

Revision ID: 1705d2ea2ea7
Revises: c6fafb9ca645
Create Date: 2022-11-17 22:35:56.999456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1705d2ea2ea7'
down_revision = 'c6fafb9ca645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'image')
    # ### end Alembic commands ###
