"""empty message

Revision ID: f32925e6c52d
Revises: 1705d2ea2ea7
Create Date: 2022-11-18 00:48:18.497546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f32925e6c52d'
down_revision = '1705d2ea2ea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Post', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Post', 'image')
    # ### end Alembic commands ###
